### ISSUE TITLE
Inquiry about missing folders and dataset

### ISSUE THREAD

**Issue by Sidd131202** [sarimmehdi/master_thesis#2]
Hi, 
I want to use your code for lane change detection, but i have few questions: 

Dataset Version: Could you specify the KITTI dataset version you used, or where I can download it for your code?
Missing Folders: I don't have "fake_velodyne," "DETS3D," and "DETS2D" folders for the dataset 3d object detection . Are they necessary, and if yes, where can I find them?

**Comment by sarimmehdi** [comment]
"fake_velodyne," "DETS3D," and "DETS2D" are needed. If KITTI website is no longer providing them, then you will have to provide them yourselves. Good luck
